### ISSUE TITLE
Searchable select doesn't reevaluate closure options

### ISSUE THREAD

**Issue by ainesophaur** [filamentphp/filament#2250]
### Package

filament/forms

### Package Version

v2.11.0

### Laravel Version

9.9

### Livewire Version

v2.10.5

### PHP Version

8.1.4

### Bug description

Using a `BelongsToSelect` with a `options` callable, I set the available options for the select using a dependent sibiling's value by calling `$get('the_dependent_field')`. 

When changing the dependents value, a non searchable select correctly updates with the values. However, if the select is marked as searchable, the options callable is called on the backend (confirmed by logging) but the select `listboxOptionsList` contains the original values from the dependent.

### Steps to reproduce

without searchable
```php
protected function getManageTicketFormSchema(): array
    {
        return [
Forms\Components\BelongsToSelect::make('ticket_board_id')
                        ->relationship('ticketBoard', 'name')
                        ->options(fn() => TicketBoard::all()->pluck('name', 'id'))
                        ->searchable()
                        ->label('Ticket Board')
                        ->reactive(),
Forms\Components\BelongsToSelect::make('ticket_status_id')
                        ->relationship('ticketStatus', 'name')
                        ->options(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->allAllowedStatuses->pluck('name', 'id'))
                        ->default(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->new_ticket_status_id)
                        ->label('Status')
                        ->placeholder("Select One")
                        ->disablePlaceholderSelection()
//                        ->searchable()
    ]
}
```
### initial state
<img width="317" alt="Screen Shot 2022-04-28 at 11 14 28 AM" src="https://user-images.githubusercontent.com/4686198/165785730-8802a909-1c56-4e4c-8a90-5024afb712c2.png">
ne")
### changed dependent
<img width="292" alt="Screen Shot 2022-04-28 at 11 14 35 AM" src="https://user-images.githubusercontent.com/4686198/165785728-da448ec2-0aa8-4f64-85b9-3ebc1d5a1966.png">

with searchable
```php
protected function getManageTicketFormSchema(): array
    {
        return [
Forms\Components\BelongsToSelect::make('ticket_board_id')
                        ->relationship('ticketBoard', 'name')
                        ->options(fn() => TicketBoard::all()->pluck('name', 'id'))
                        ->searchable()
                        ->label('Ticket Board')
                        ->reactive(),
Forms\Components\BelongsToSelect::make('ticket_status_id')
                        ->relationship('ticketStatus', 'name')
                        ->options(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->allAllowedStatuses->pluck('name', 'id'))
                        ->default(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->new_ticket_status_id)
                        ->label('Status')
                        ->placeholder("Select One")
                        ->disablePlaceholderSelection()
                        ->searchable()
    ]
}
```
<img width="313" alt="Screen Shot 2022-04-28 at 11 17 26 AM" src="https://user-images.githubusercontent.com/4686198/165786376-4380d30d-b4a8-499d-ab6a-25e138b2f03b.png">
<img width="292" alt="Screen Shot 2022-04-28 at 11 17 39 AM" src="https://user-images.githubusercontent.com/4686198/165786398-bee43e23-7cbc-4cb0-b5c4-873c97d4142d.png">

### Relevant log output

```shell
--- original options populated when the form was filled ---
[2022-04-28 14:46:13] local.INFO: populating ticket status {"board":18276486811313,"result":{"Illuminate\\Support\\Collection":{"18276486707790":"New","18276486941448":"Updated","18276486966929":"Waiting","18276486746643":"Closed"}}} 

--- after changing the dependent select ---
[2022-04-28 14:46:21] local.INFO: populating ticket status {"board":"18494810344534","result":{"Illuminate\\Support\\Collection":{"18276486707790":"New","18276486746643":"Closed"}}}
```

**Comment by ainesophaur** [comment]
I upgraded to `v2.11.8` and the issue seems to persist. I ran the following per the upgrade docs

```shell
php artisan config:clear
php artisan view:clear
```

**Comment by danharrin** [comment]
#2057 is still an open PR, it has not been finished yet

**Comment by ainesophaur** [comment]
This issue still exists in current versions. The child dependent field cannot be marked `searchable()`. If a child dependent filed is marked `searchable()` it does not re-evaluate its options (even though they're updated as far as the server is concerned)

I can leave the parent field as searchable and the child field as non-searchable and achieve the desired behavior. It seems like this could be an issue within the alpine component.

**Comment by ryangjchandler** [comment]
I've noticed this same problem in my Navigation plugin. Haven't dug into it yet.

**Comment by danharrin** [comment]
I think I just made a mistake when I merged the select fields together the other day.

**Comment by danharrin** [comment]
Does #2922 fix this @ainesophaur @ryangjchandler

**Comment by ainesophaur** [comment]
For my issue (not sure if its the same as @ryangjchandler ) fix #2922 does not solve the issue.

I updated a previous sample [repo](https://github.com/ainesophaur/filament-tags-issue-2797.git) I made (for #2797) to include a minimal sample for this issue.

Below is the relevant PHP code

```php
protected function getFormSchema(): array
    {
        return [
            Forms\Components\BelongsToSelect::make('author')
            ->relationship('author', 'name')
            ->reactive(),
            Forms\Components\BelongsToSelect::make('publisher')
            ->relationship('publisher', 'name')
            ->searchable($this->searchable)
            ->options(function($get){
                $author = $get('author');
                if(!$author){
                    info('publisher options has no author, returning all results');
                    return Publisher::all()->pluck('name', 'id');
                }
                $options = User::findOrFail($author)->publishers->pluck('name', 'id');
                info('publisher options has author', ['author' => $author, 'options' => $options]);
                return $options;
            })
        ];
    }
```


Below are the logs I write out during the fields `options()` callable to ensure that the correct results should have been returned.

```
[2022-06-25 19:21:19] local.INFO: publisher options has no author, returning all results  
[2022-06-25 19:21:19] local.INFO: publisher options has no author, returning all results  
[2022-06-25 19:21:19] local.INFO: publisher options has no author, returning all results  
[2022-06-25 19:21:31] local.INFO: publisher options has author {"author":"5","options":{"Illuminate\\Support\\Collection":{"1":"Vandervort Group"}}} 
[2022-06-25 19:21:31] local.INFO: publisher options has author {"author":"5","options":{"Illuminate\\Support\\Collection":{"1":"Vandervort Group"}}} 
[2022-06-25 19:21:31] local.INFO: publisher options has author {"author":"5","options":{"Illuminate\\Support\\Collection":{"1":"Vandervort Group"}}}
```

And below is a screen cap highlighting the issue between the behavior with non-searchable (working correctly) and searchable (not working correctly) dependent selects.

![searchable_filter_issue](https://user-images.githubusercontent.com/4686198/175787946-df66da06-9d76-4ea6-8864-421d28151dfa.gif)

**Comment by danharrin** [comment]
Okay I found your issue, you were overriding `options()` completely instead of using the documented third parameter of `relationship()`, which you can use to scope the query.

Also, it's advisable that you reset the publisher field when the author field changes.

https://user-images.githubusercontent.com/41773797/176896424-3e36d7b0-e91a-4ece-8955-6f7ff9b332ed.mov

```php
Forms\Components\Select::make('author')
    ->relationship('author', 'name')
    ->reactive()
    ->afterStateUpdated(function ($set) {
        $set('publisher', null);
    }),
Forms\Components\Select::make('publisher')
    ->relationship('publisher', 'name', function ($query, $get) {
        $author = $get('author');

        if (! $author) {
            return $query;
        }

        return $query->whereRelation('authors', 'id', $author);
    })
    ->preload()
    ->searchable($this->searchable),
```

**Comment by ainesophaur** [comment]
Ill give the above a shot. Thank you so much for digging into it. FWIW, I used the approach I seen demonstrated [in the docs](https://filamentphp.com/docs/2.x/forms/fields#dependant-selects) It might be worth mentioning in the docs to use the relationship third param approach.

**Comment by danharrin** [comment]
Ah I see, that dependant select video does not cover `relationship()` though, the approach will still work if you don't use that.
